#!/usr/bin/env node
// Bundle index.html + src/*.js + Three.js into one self-contained HTML file that runs
// from disk with no network: each module is embedded as text, turned into a blob URL
// at load time, and wired together with a generated import map.
//
//   npm i three@0.185.1            (anywhere; pass its folder with --three)
//   node build_offline.mjs --three <node_modules/three> --out particle-voxel-head.offline.html

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : fallback;
};
const threeDir = resolve(arg('--three', join(here, 'node_modules/three')));
const out = resolve(arg('--out', join(here, 'particle-voxel-head.offline.html')));

const read = (p) => readFileSync(p, 'utf8');
const threeVersion = JSON.parse(read(join(threeDir, 'package.json'))).version;
const modules = {
  'three-core': read(join(threeDir, 'build/three.core.min.js')),
  three: read(join(threeDir, 'build/three.module.min.js')).replaceAll('from"./three.core.min.js"', 'from"three-core"'),
  'app/heads': read(join(here, 'src/heads.js')),
  'app/shaders': read(join(here, 'src/shaders.js')),
  'app/main': read(join(here, 'src/main.js'))
    .replace("from './heads.js'", "from 'app/heads'")
    .replace("from './shaders.js'", "from 'app/shaders'"),
};
if (!modules.three.includes('from"three-core"')) throw new Error('three.module.min.js import shape changed; update the rewrite');
for (const [id, code] of Object.entries(modules)) {
  if (/<\/script/i.test(code)) throw new Error(`${id} contains a closing script tag; cannot embed as text`);
}

const embedded = Object.entries(modules)
  .map(([id, code]) => `<script type="text/plain" data-module="${id}"${id === 'app/heads' ? ' id="heads-src"' : ''}>${code}</script>`)
  .join('\n');
const loader = `<script>
// Offline loader: embedded modules -> blob URLs -> import map -> entry.
(() => {
  const imports = {};
  for (const el of document.querySelectorAll('script[data-module]')) {
    imports[el.dataset.module] = URL.createObjectURL(new Blob([el.textContent], { type: 'text/javascript' }));
  }
  const map = document.createElement('script');
  map.type = 'importmap';
  map.textContent = JSON.stringify({ imports });
  document.head.appendChild(map);
  import('app/main').catch((e) => {
    document.getElementById('status').textContent = 'failed to start: ' + e.message;
    console.error(e);
  });
})();
</script>`;

let html = read(join(here, 'index.html'));
html = html.replace(/<script type="importmap">[\s\S]*?<\/script>\n?/, '');
html = html.replace(/<!-- Development entry\.[^>]*-->\n?/, `<!-- Offline build: Three.js ${threeVersion} embedded. Generated by build_offline.mjs; edit the sources instead. -->\n`);
// Function replacement: minified code contains `$'`/`$&`, which a string replacement
// would expand as patterns and silently corrupt.
html = html.replace('<script type="module" src="./src/main.js"></script>', () => `${embedded}\n${loader}`);
for (const [id, code] of Object.entries(modules)) {
  if (!html.includes(code)) throw new Error(`${id} was not embedded verbatim`);
}
writeFileSync(out, html);
console.log(JSON.stringify({ out, bytes: Buffer.byteLength(html), three: threeVersion }));
